# <center> Compute adaptive weight for ANN </center>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#INTRODUCTION" data-toc-modified-id="INTRODUCTION-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>INTRODUCTION</a></span></li><li><span><a href="#PROBLEM" data-toc-modified-id="PROBLEM-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>PROBLEM</a></span></li><li><span><a href="#SOLUTION" data-toc-modified-id="SOLUTION-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>SOLUTION</a></span><ul class="toc-item"><li><span><a href="#Forward-Propagation" data-toc-modified-id="Forward-Propagation-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Forward Propagation</a></span></li><li><span><a href="#Back-Propagation" data-toc-modified-id="Back-Propagation-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Back Propagation</a></span></li></ul></li><li><span><a href="#CONCLUSIONS" data-toc-modified-id="CONCLUSIONS-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>CONCLUSIONS</a></span></li></ul></div>

##  INTRODUCTION

This project will calculate the updated weight for the the first iteration of a ANN with 2 layers by using given weights for all these layers and initialize bias as well as learning rate.

## PROBLEM

In [1]:
import numpy as np

![title](problem.png)


**=> Initialize bias for layers = 0 (example x0 = 1 w0 = 0  -> x0*w0 = 0, bias layer 1 = 0)**

!['Diagram'](Diagram.png)

Matrix of weights for layers 1 and 2 as follow (bias = 0 so they are not added to matrice):

Weights of layer 1 
$ W1 = \begin{bmatrix}
    w1j & w2j & w3j
  \\w1i & w2i & w3i 
\end{bmatrix}$

Weights of layer 2 
$ W2 = \begin{bmatrix}
    wjk & wik    
\end{bmatrix}$


In [2]:
W1=np.array([[0.2, 0.3, -0.1],
             [0.1, -0.1, 0.2]])
W1

array([[ 0.2,  0.3, -0.1],
       [ 0.1, -0.1,  0.2]])

In [3]:
W2=np.array([0.1, 0.5])
W2 = W2.reshape(1,2)
W2

array([[0.1, 0.5]])

In [4]:
X = np.array([[1], [0.4], [0.7]])
X

array([[1. ],
       [0.4],
       [0.7]])

**The activation function used in this project is sigmoid function $sig = \frac{1}{1+e^{-z}}$**

## SOLUTION

### Forward Propagation

Output Matrix of Layer 1 is $ O1 = \begin{bmatrix}
    Oj
  \\Oi 
\end{bmatrix}=$ 
$\begin{bmatrix}
    sig( w1j*x1 + w2j*x2 + w3j*x3)
  \\sig( w1i*x1 + w2i*x2 + w3i*x3) 
\end{bmatrix}$


In [5]:
def SigmoidFunc(num):
    return 1/(1 + np.exp(- num))

In [6]:
O1 = SigmoidFunc(np.dot(W1,X))
O1

array([[0.5621765],
       [0.549834 ]])

Output Matrix of Layer 2 is $ O2 = \begin{bmatrix}
    Ok 
\end{bmatrix}=$
$\begin{bmatrix}
    sig( wjk*O1 + wik*O2)
\end{bmatrix}$

In [7]:
O2 = SigmoidFunc(np.dot(W2,O1))
O2

array([[0.58203543]])

### Back Propagation

Error function

![aaa](Error.png)

**Define tk = 0.8**

In [8]:
tk = 0.8

![ASDA](BackForm.png)

Derivative weights of layer 1 
$ dW1 = \begin{bmatrix}
    dw1j & dw2j & dw3j
  \\dw1i & dw2i & dw3i 
\end{bmatrix}$

Derivative weights of layer 2 
$ dW2 = \begin{bmatrix}
    dwjk & dwik    
\end{bmatrix}$

$$dW2 = \frac{de}{dO2} * \frac{dO2}{dZ2} * \frac{dZ2}{dW2}$$



$\frac{de}{dO2} = - (tk - 02) $

$\frac{dO2}{dZ2} = O2(1-O2)$

$\frac{dZ2}{dW2} = O1$

In [9]:
dW2 = np.dot(-(tk - O2)*O2*(1 - O2),O1.T)
dW2

array([[-0.02980901, -0.02915455]])

$$dW1 = \frac{de}{dO2} * \frac{dO2}{dZ2} * \frac{dZ2}{dO1} * \frac{dO1}{dZ1} * \frac{dZ1}{dW1}$$



$\frac{dZ2}{dO1} = W2$

$\frac{dO1}{dZ1} = O1(1-O1)$

$\frac{dZ1}{dW1} = X$

In [10]:
W2.shape

(1, 2)

In [11]:
dW1 = np.dot(-(tk - O2)*O2*(1 - O2)*W2.T*O1*(1-O1),X.T)
dW1

array([[-0.00130511, -0.00052204, -0.00091358],
       [-0.00656219, -0.00262488, -0.00459354]])

**Define Learning rate $\eta = 0.1$**

**Update Weight:**
    
$$ W1 = W1 - \eta*dW1 $$

$$ W2 = W2 - \eta*dW2 $$

In [12]:
learning_rate = 0.1
updW1 = W1 - learning_rate*dW1
updW2 = W2 - learning_rate*dW2

In [13]:
updW1

array([[ 0.20013051,  0.3000522 , -0.09990864],
       [ 0.10065622, -0.09973751,  0.20045935]])

In [14]:
updW2

array([[0.1029809 , 0.50291546]])

**updW1 and updW2 contain the updated in 1st iteration**

## CONCLUSIONS

After the 1st iteration the updated weighs are

In [15]:
indexLst = ['w1j','w2j','w3j','w1i','w2i','w3i','wjk','wik']
lisUpdWeights = np.squeeze(updW1.reshape(6,1)).tolist() + np.squeeze(updW2.reshape(2,1)).tolist()
lisUpdWeights = np.round(lisUpdWeights,8)
lisWeigh = [0.2, 0.3, -0.1, 0.1, -0.1, 0.2, 0.1, 0.5]

In [16]:
import pandas as pd
data = {'Weights':lisWeigh,
        'Updated_Weights': lisUpdWeights}
dataframe = pd.DataFrame(index = indexLst, data = data)

In [17]:
dataframe

Weights  Updated_Weights
w1j      0.2         0.200131
w2j      0.3         0.300052
w3j     -0.1        -0.099909
w1i      0.1         0.100656
w2i     -0.1        -0.099738
w3i      0.2         0.200459
wjk      0.1         0.102981
wik      0.5         0.502915

**=> After the 1st iteration, table above shows the result**